version: "3.8"

services:
    django:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: django
      develop:
       watch:
        - action: rebuild
          path: ./
      ports:
        - "8000:8000"
    redis:
     image: redis:7.2.5-alpine
     container_name: redis
     ports:
      - "6379:6379"

