# Generated by Django 5.0 on 2024-02-22 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepicture', models.ImageField(upload_to='images')),
                ('banner', models.ImageField(blank=True, upload_to='images')),
                ('about', models.TextField()),
                ('collabs', models.IntegerField(blank=True, default=0, null=True)),
                ('bugcrowd', models.CharField(blank=True, max_length=150)),
                ('twitter', models.CharField(blank=True, max_length=150)),
                ('fb', models.CharField(blank=True, max_length=150)),
                ('insta', models.CharField(blank=True, max_length=150)),
                ('phone', models.BigIntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
