# Generated by Django 5.0 on 2024-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_posts_collaborate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
