# Generated by Django 4.2 on 2024-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_collaborate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('dateposted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
