# Generated by Django 4.2 on 2024-02-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychats',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mychats',
            name='time',
            field=models.TimeField(auto_now_add=True, default='2024-02-28'),
            preserve_default=False,
        ),
    ]
