# Generated by Django 4.2 on 2024-02-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='username',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
